### ISSUE TITLE
No module named 'mypy_protobuf'

### ISSUE THREAD

**Issue by happyli0826** [so1n/protobuf_to_pydantic#3]
python -m grpc_tools.protoc -I. --protobuf-to-pydantic_out=. proxy.proto  

Traceback (most recent call last):
  File "/Users/wangmingli/.local/share/virtualenvs/pythonProject3-USoLf3Xu/bin/protoc-gen-protobuf-to-pydantic", line 5, in <module>
    from protobuf_to_pydantic.plugin.main import main
  File "/Users/wangmingli/.local/share/virtualenvs/pythonProject3-USoLf3Xu/lib/python3.8/site-packages/protobuf_to_pydantic/plugin/main.py", line 13, in <module>
    from mypy_protobuf.main import Descriptors, code_generation
ModuleNotFoundError: No module named 'mypy_protobuf'
--protobuf-to-pydantic_out: protoc-gen-protobuf-to-pydantic: Plugin failed with status code 1.
(pythonProject3) (base) wangmingli@wangminglidemac pythonProject3 % python -m grpc_tools.protoc -I. --protobuf-to-pydantic_out=. proxy.proto
Traceback (most recent call last):
  File "/Users/wangmingli/.local/share/virtualenvs/pythonProject3-USoLf3Xu/bin/protoc-gen-protobuf-to-pydantic", line 5, in <module>
    from protobuf_to_pydantic.plugin.main import main
  File "/Users/wangmingli/.local/share/virtualenvs/pythonProject3-USoLf3Xu/lib/python3.8/site-packages/protobuf_to_pydantic/plugin/main.py", line 13, in <module>
    from mypy_protobuf.main import Descriptors, code_generation
ModuleNotFoundError: No module named 'mypy_protobuf'
--protobuf-to-pydantic_out: protoc-gen-protobuf-to-pydantic: Plugin failed with status code 1.
(pythonProject3) (base) wangmingli@wangminglidemac pythonProject3 % python -m grpc_tools.protoc -I. --protobuf-to-pydantic_out=config_path=plugin_config.py:. proxy.proto 
Traceback (most recent call last):
  File "/Users/wangmingli/.local/share/virtualenvs/pythonProject3-USoLf3Xu/bin/protoc-gen-protobuf-to-pydantic", line 5, in <module>
    from protobuf_to_pydantic.plugin.main import main
  File "/Users/wangmingli/.local/share/virtualenvs/pythonProject3-USoLf3Xu/lib/python3.8/site-packages/protobuf_to_pydantic/plugin/main.py", line 13, in <module>
    from mypy_protobuf.main import Descriptors, code_generation
ModuleNotFoundError: No module named 'mypy_protobuf'
--protobuf-to-pydantic_out: protoc-gen-protobuf-to-pydantic: Plugin failed with status code 1.

**Comment by so1n** [comment]
Generating the pydantic.BaseModel code file directly via the plugin requires the installation of the mypy-protobuf module (python -m pip install protobuf-to-pydanitc[mypy-protobuf])
