### ISSUE TITLE
feat: Handle google protobuf FieldMask

### ISSUE THREAD

**Issue by Dr0p42** [so1n/protobuf_to_pydantic#43]
**Is your feature request related to a problem? Please describe.**
I would like to use FieldMask, but I have an error when I try to do so:

```proto
syntax = "proto3";

package chat;

import "google/protobuf/field_mask.proto";
import "google/protobuf/struct.proto";
import "validate.proto";


...

message ChatUpdate {
    optional string name = 1;
    optional bool is_group = 2;
    optional bool is_personal_assistant = 3;
    optional string starred_at = 4;

    optional google.protobuf.FieldMask field_mask = 100;
}
```

When I try to convert my protos, I get this:

```
docker run --rm -it -v `pwd`:/data --workdir /data naas-models-builder:latest python3 -m grpc_tools.protoc \
                -I=protos \
                -I=/usr/local/include/include/google/protobuf \
                -I=lib/protoc-gen-validate/validate \
                --protobuf-to-pydantic_out=python/naas_models/pydantic \
                --python_out=python/naas_models \
                --go_out=go \
                --validate_out="lang=go:go" \
                space.proto registry.proto iam.proto aimodel.proto chat.proto credit.proto secret.proto workspace.proto validate.proto
iam.proto:7:1: warning: Import validate.proto is unused.
chat.proto:9:1: warning: Import google/protobuf/struct.proto is unused.
credit.proto:7:1: warning: Import validate.proto is unused.
secret.proto:7:1: warning: Import validate.proto is unused.
parse command-line error:not enough values to unpack (expected 2, got 1)
Writing protobuf-to-pydantic code to space_p2p.py
Writing protobuf-to-pydantic code to registry_p2p.py
Writing protobuf-to-pydantic code to iam_p2p.py
Writing protobuf-to-pydantic code to aimodel_p2p.py
Not support type .google.protobuf.FieldMask
Traceback (most recent call last):
  File "/usr/local/bin/protoc-gen-protobuf-to-pydantic", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/protobuf_to_pydantic/plugin/main.py", line 67, in main
    generate_pydantic_model(Descriptors(request), response, parse_param(request))
  File "/usr/local/lib/python3.10/dist-packages/protobuf_to_pydantic/plugin/main.py", line 32, in generate_pydantic_model
    file.content = config.file_descriptor_proto_to_code(fd=fd, descriptors=descriptors, config=config).content
  File "/usr/local/lib/python3.10/dist-packages/protobuf_to_pydantic/plugin/field_desc_proto_to_code.py", line 53, in __init__
    self._parse_field_descriptor()
  File "/usr/local/lib/python3.10/dist-packages/protobuf_to_pydantic/plugin/field_desc_proto_to_code.py", line 396, in _parse_field_descriptor
    self._content_deque.append(self._message(desc, [FileDescriptorProto.ENUM_TYPE_FIELD_NUMBER]))
  File "/usr/local/lib/python3.10/dist-packages/protobuf_to_pydantic/plugin/field_desc_proto_to_code.py", line 309, in _message
    if field.type == 11 and self._get_protobuf_type_model(field).type_factory is AnyMessage:
  File "/usr/local/lib/python3.10/dist-packages/protobuf_to_pydantic/plugin/field_desc_proto_to_code.py", line 379, in _get_protobuf_type_model
    return ProtobufTypeModel(
  File "/usr/local/lib/python3.10/dist-packages/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for ProtobufTypeModel
rule_type_str
  none is not an allowed value (type=type_error.none.not_allowed)
--protobuf-to-pydantic_out: protoc-gen-protobuf-to-pydantic: Plugin failed with status code 1.
make: *** [generate] Error 1
```

**Describe the solution you'd like**

I would just like the FieldMask to work by default. 

**Describe alternatives you've considered**

I considered created my own version of the `FieldMask` message but I would like to avoid this:

```proto
message FieldMask {
    // The set of field mask paths.
    repeated string paths = 1;
  }

message ChatUpdate {
    optional string name = 1;
    optional bool is_group = 2;
    optional bool is_personal_assistant = 3;
    optional string starred_at = 4;

    FieldMask field_mask = 100;
}
```

**Comment by Dr0p42** [comment]
I just updated to `0.2.5` and it's not failing anymore but it's still saying that it's not supported:

```
docker run --rm -it -v `pwd`:/data --workdir /data naas-models-builder:latest python3 -m grpc_tools.protoc \
                -I=protos \
                -I=/usr/local/include/include/google/protobuf \
                -I=lib/protoc-gen-validate/validate \
                --protobuf-to-pydantic_out=python/naas_models/pydantic \
                --python_out=python/naas_models \
                --go_out=go \
                --validate_out="lang=go:go" \
                space.proto registry.proto iam.proto aimodel.proto chat.proto credit.proto secret.proto workspace.proto validate.proto
iam.proto:7:1: warning: Import validate.proto is unused.
chat.proto:9:1: warning: Import google/protobuf/struct.proto is unused.
credit.proto:7:1: warning: Import validate.proto is unused.
secret.proto:7:1: warning: Import validate.proto is unused.
Writing protobuf-to-pydantic code to space_p2p.py
Writing protobuf-to-pydantic code to registry_p2p.py
Writing protobuf-to-pydantic code to iam_p2p.py
Writing protobuf-to-pydantic code to aimodel_p2p.py
Not support type .google.protobuf.FieldMask
Not support type .google.protobuf.FieldMask
Writing protobuf-to-pydantic code to chat_p2p.py
Writing protobuf-to-pydantic code to credit_p2p.py
Writing protobuf-to-pydantic code to secret_p2p.py
Writing protobuf-to-pydantic code to workspace_p2p.py
cd python/naas_models && sed -i.bak  's/import validate_pb2/import naas_models.validate_pb2/g' *.py && rm *.bak
```

**Comment by Dr0p42** [comment]
> Thanks for the feedback and suggestion, I will support this feature in the near future!

Awesome, thank you @so1n.
